version: "2.1"
services:
  localise-db:
    container_name: template-db
    image: postgres:10
    ports:
      - 5444:5432
    environment:
      - POSTGRES_DB=template
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234567
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./data/localise-db:/var/lib/postgresql/data


