definitions:
  datamodels.User:
    properties:
      age:
        type: integer
      first_name:
        type: string
      id:
        type: string
      last_name:
        type: string
    type: object
  errs.ErrWrapper:
    properties:
      code:
        example: 500
        type: integer
      message:
        example: INTERNAL_SERVER_ERROR
        type: string
    type: object
host: localhost:1123
info:
  contact: {}
  license: {}
  title: Template
  version: "1.0"
paths:
  /users:
    post:
      consumes:
      - application/json
      description: get test user model
      parameters:
      - description: it is id
        in: body
        name: JSON
        required: true
        schema:
          $ref: '#/definitions/datamodels.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            Token:
              description: JWT token
              type: string
          schema:
            $ref: '#/definitions/datamodels.User'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errs.ErrWrapper'
      security:
      - bearerAuth: []
      summary: Show an account
      tags:
      - users
securityDefinitions:
  bearerToken:
    in: Header
    name: Authorization
    type: apiKey
swagger: "2.0"
